= crystal-asciidoctor-epub
:toc: left
:toclevels: 2

AsciiDoc to EPUB3 converter for Crystal, equivalent of the https://github.com/asciidoctor/asciidoctor-epub3[asciidoctor-epub3] Ruby gem.

link:README.fr.adoc[Version française]

== Features

* Converts AsciiDoc documents to valid EPUB3 files
* Sections, paragraphs, lists (ordered/unordered), tables
* Code blocks, admonitions, blockquotes, verses, sidebars
* Images, thematic breaks
* Table of contents (NCX + EPUB3 NAV)
* PDF bookmarks equivalent (NCX navigation)
* Metadata: title, author, language, description, publisher
* Cover image support
* Default stylesheet included
* **Library API** for use in web applications
* **CLI** for command-line usage

== Installation

=== As a library

Add to your `shard.yml`:

[source,yaml]
----
dependencies:
  crystal-asciidoctor-epub:
    github: aloli-crystal/crystal-asciidoctor-epub
    version: "~> 0.1"
----

Then run `shards install`.

=== CLI binary

[source,bash]
----
git clone https://github.com/aloli-crystal/crystal-asciidoctor-epub.git
cd crystal-asciidoctor-epub
shards build --release
sudo cp bin/crystal-asciidoctor-epub /usr/local/bin/
----

== Usage

=== Library API

[source,crystal]
----
require "asciidoctor_epub"

input = <<-ADOC
= My Book
Author Name
:lang: en

== Chapter 1

This is the first chapter with *bold* and _italic_.

== Chapter 2

A code example:

[source,crystal]
\----
puts "Hello!"
\----
ADOC

doc = Asciidoctor.load(input)

# Get EPUB as bytes (for web applications)
bytes = AsciidoctorEpub::Converter.new.convert(doc)

# Or write directly to file
AsciidoctorEpub::Converter.new.convert_to_file(doc, "my-book.epub")
----

=== In a Kemal web application

[source,crystal]
----
require "kemal"
require "asciidoctor_epub"

post "/generate-epub" do |env|
  content = env.params.body["content"]
  doc = Asciidoctor.load(content)
  epub_bytes = AsciidoctorEpub::Converter.new.convert(doc)

  env.response.content_type = "application/epub+zip"
  env.response.headers["Content-Disposition"] = "attachment; filename=document.epub"
  env.response.write(epub_bytes)
end

Kemal.run
----

=== Command line

[source,bash]
----
crystal-asciidoctor-epub document.adoc
# => Generates document.epub
----

Options:

[cols="1,3"]
|===
| Option | Description

| `-o FILE`, `--out-file FILE`
| Output EPUB file (default: `<input>.epub`)

| `-v`, `--version`
| Show version

| `-h`, `--help`
| Show help
|===

== Versions

[cols="2,2,2"]
|===
| | Version | Date

| *Ruby asciidoctor-epub3 (reference)*
| 2.3.0
| 2025-08-31

| *Ruby asciidoctor (parser, via crystal-asciidoctor)*
| 2.0.26
| 2025-10-24

| *crystal-asciidoctor-epub*
| 0.1.0
| 2026-04-12
|===

== Development

[source,bash]
----
git clone https://github.com/aloli-crystal/crystal-asciidoctor.git
git clone https://github.com/aloli-crystal/crystal-asciidoctor-epub.git
cd crystal-asciidoctor-epub
shards install
crystal spec
----

== License

MIT
